build: off

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

install:
# OpenJDK installation via: https://chocolatey.org/packages/openjdk
#  - choco install openjdk --version 11.0.2
#  - SET JAVA_HOME="C:\Program Files\OpenJDK\jdk-11.0.2"
# Or use pre-installed JDK: https://www.appveyor.com/docs/windows-images-software/#java
  - SET JAVA_HOME="C:\Program Files\Java\jdk11"
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version

test_script:
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace build publishToMavenLocal
  - gradlew --no-daemon --stacktrace -Dplatform.tooling.support.tests.enabled=true build
