build: off

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

install:
  - cinst jdk10 -params 'installdir=C:\\jdk10'
  - SET JAVA_HOME=C:\jdk10
  - SET PATH=C:\jdk10\bin;%PATH%

test_script:
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace build publishToMavenLocal
  - gradlew --no-daemon --stacktrace -Dplatform.tooling.support.tests.enabled=true build
