build: off

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

install:
# OpenJDK installation via: https://chocolatey.org/packages/openjdk
#  - choco install openjdk --version 11.0.2
#  - SET JAVA_HOME="C:\Program Files\OpenJDK\jdk-11.0.2"
# Or use pre-installed JDK: https://www.appveyor.com/docs/windows-images-software/#java
  - SET JAVA_HOME="C:\Program Files\Java\jdk11"
  - SET PATH=%JAVA_HOME%\bin;%PATH%
  - java -version

test_script:
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace build publishToMavenLocal
  - gradlew --no-daemon --stacktrace -Dplatform.tooling.support.tests.enabled=true build

notifications:
  - provider: Slack
    incoming_webhook:
      secure: yuiEy7Tlmr5iHbBQqpwb5XNC83j4Mexcz/4jVGeuzeEluQ5wkksdDmqP+CV2yFudxYHG8T/JqNTQF1RNftw26PmkL426mj3QzrwbQU6O5H0=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
