language: java

sudo: false
dist: trusty

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

matrix:
  include:
# Java 9 "Oracle JDK" (provided by Travis CI)
    - jdk: oraclejdk9
      env: JDK_RELEASE='Oracle JDK 9' EXTRA_GRADLE_ARGS='-PenableJaCoCo'
      install: echo "Don't let Travis CI execute './gradlew assemble' by default"
# Java 9 "OpenJDK"
    - env: JDK_RELEASE='OpenJDK 9' EXTRA_GRADLE_ARGS=''
      install: . ./src/install/install-jdk.sh -F 9 -L GPL
# Java 10 "Oracle JDK"
    - env: JDK_RELEASE='Oracle JDK 10' EXTRA_GRADLE_ARGS=''
      install: . ./src/install/install-jdk.sh -F 10 -L BCL
# Java 10 "OpenJDK"
    - env: JDK_RELEASE='OpenJDK 10' EXTRA_GRADLE_ARGS=''
      install: . ./src/install/install-jdk.sh -F 10 -L GPL

script:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version
# Build JUnit 5
  - ./gradlew build $EXTRA_GRADLE_ARGS --scan --stacktrace -Dkotlin.compiler.execution.strategy="in-process"

# Do not store unnecessary files from Gradle dependency cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Store Gradle dependency cache and Gradle Wrapper files for next execution
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Run clover report and send report to codecov after build success for JDK 9 builds
after_success:
  - test "$JDK_RELEASE" = "Oracle JDK 9" && ./gradlew -PenableJaCoCo jacocoRootReport || true
  - test "$JDK_RELEASE" = "Oracle JDK 9" && bash <(curl -s https://codecov.io/bash) || true
