[[api-evolution]]
== APIの進化

JUnit 5の主要な目的の1つは、JUnitが多くのプロジェクトで使われていたとしても、
メンテナがJUnitを進化させられるようにすることです。
JUnit 4では多くの部品が元々は内部用途で追加されましたが、
外部の拡張機能やツールの作者から使われることになりました。
そのせいで、JUnit 4の変更はとりわけ難しく、ときには不可能になりました。

JUnit 5がすべての公開インターフェースやクラス、メソッドに対して明確に定義された
ライフサイクルを導入したのはこのためです。

[[api-evolution-version-and-status]]
=== APIバージョンとステータス

公開されているモジュールは `<major>.<minor>.<patch>` というバージョン番号をもち、
すべての公開インターフェース、クラス、メソッドには {API_Guardian} プロジェクトの
{API} アノテーションが付与されています。このアノテーションの `status` 属性には、
次のいずれかの値が設定されています。

[cols="20,80"]
|===
| ステータス           | 説明

| `INTERNAL`       | JUnit自身以外のコードで使ってはならない。事前予告なしに削除されうる。
| `DEPRECATED`     | もう使うべきではない。次のマイナー (minor) リリースで削除されうる。
| `EXPERIMENTAL`   | フィードバックがほしい実験的な新機能を意味する。注意して使うべき。 +
                     将来 `MAINTAINED` または `STABLE` に昇格される可能性がある一方で、
                     パッチ (patch) リリースでも事前予告なしに削除されうる。
| `MAINTAINED`     | 現在のメジャー (major) バージョンの *少なくとも* 次のマイナー (minor)
                     リリースでは、後方互換性がない方法で変更されることがない機能を意味する。
                     削除予定になった場合は、まず最初に `DEPRECATED` に降格される。
| `STABLE`         | 現在のメジャーバージョン (`5.*`) の間は、
                     後方互換性がない方法で変更されることがない機能を意味する。
|===

`@API` アノテーションが型に付与された場合、その型のすべての公開メンバーに適用されているとみなします。
個々のメンバーは、より低い安定度をもつ異なる `status` 属性を宣言することができます。

[[api-evolution-experimental-apis]]
=== 実験的なAPI

次の表は、現在 _実験的_ (`@API(status = EXPERIMENTAL)`) と指定されたAPIを一覧しています。
これらのAPIを使う場合は注意してください。

include::{experimentalApisTableFile}[]

[[api-evolution-tooling]]
=== @APIツールサポート

{API_Guardian} プロジェクトは、 {API} アノテーションが付与されたAPIの提供者や利用者のために、
ツールによるサポートを計画しています。例えば、JUnitのAPIが `@API`
アノテーションの宣言にしたがって使われているかをチェックする手段を提供するなどです。
