[[appendix]]
== 付録

[[dependency-metadata]]
=== 依存関係メタデータ

最終リリースや各マイルストーンでの成果物は {Maven_Central} にデプロイされ、
スナップショットは Sonatype {snapshot-repo}[スナップショットリポジトリ] の
{snapshot-repo}/org/junit/[/org/junit] 以下にデプロイされています。

[[dependency-metadata-junit-platform]]
==== JUnit Platform

* *Group ID*: `org.junit.platform`
* *Version*: `{platform-version}`
* *Artifact IDs*:
  `junit-platform-commons`::
    JUnit Platform のための共通 API とサポートユーティリティです。`@API(status = INTERNAL)`
    アノテーションの付与された API は、JUnit フレームワーク自身で使われることだけを想定しています。
    _外部のプログラムからの内部 API の利用はサポートされていません！_
  `junit-platform-console`::
    コンソールから JUnit Platform 上でテストを見つけて実行する機能を提供します。
    詳細は、<<running-tests-console-launcher>> を参照してください。
  `junit-platform-console-standalone`::
    すべての依存関係を含む実行可能な JAR は、Maven Central リポジトリの
    https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone[junit-platform-console-standalone]
    ディレクトリで提供されています。詳細は、<<running-tests-console-launcher>> を参照してください。
  `junit-platform-engine`::
    テストエンジンの公開 API です。詳細は、<<launcher-api-engines-custom>> を参照してください。
  `junit-platform-launcher`::
    テストプランを構成して起動するための公開 API です。通常は、IDE やビルドツールに使われます。
    詳細は、<<launcher-api>> を参照してください。
  `junit-platform-reporting`::
    テストレポートを生成するための `TestExecutionListener` 実装です。通常は、IDE やビルドツールに使われます。
    詳細は、<<launcher-api-listeners-reporting>> を参照してください。
  `junit-platform-runner`::
    JUnit Platform 上のテストおよびテストスイートを JUnit 4 環境で実行するテストランナーです。
    詳細は、<<running-tests-junit-platform-runner>> を参照してください。
  `junit-platform-suite-api`::
    JUnit Platform 上でテストスイートを構成するためのアノテーションです。
    <<running-tests-junit-platform-runner,JUnitPlatform ランナー>> と（おそらく）
    サードパーティーの `TestEngine` 実装にもサポートされます。
  `junit-platform-testkit`::
     与えられた `TestEngine` でテストプランを実行し、流れるような API を使って
     テスト結果が期待通りかを検証するためのサポートを提供します。

[[dependency-metadata-junit-jupiter]]
==== JUnit Jupiter

* *Group ID*: `org.junit.jupiter`
* *Version*: `{jupiter-version}`
* *Artifact IDs*:
  `junit-jupiter`::
    Gradle や Maven のようなビルドツールで依存関係の管理を簡易化するために、
    `junit-jupiter-api` と `junit-jupiter-params`、`junit-jupiter-engine`
    への依存をまとめて追加するための JUnit Jupiter 集約アーティファクトです。
  `junit-jupiter-api`::
    <<writing-tests,テスト>> や <<extensions,拡張機能>> を書くための JUnit Jupiter API です。
  `junit-jupiter-engine`::
    JUnit Jupiter のテストエンジン実装です。実行時だけ必要になります。
  `junit-jupiter-params`::
    JUnit Jupiter で <<writing-tests-parameterized-tests,パラメーター化テスト>> をサポートします。
  `junit-jupiter-migrationsupport`::
    JUnit 4 から JUnit Jupiter への移行をサポートします。JUnit 4 の `@Ignore`
    アノテーションと選択した JUnit 4 ルールを実行したいときだけ必要になります。

[[dependency-metadata-junit-vintage]]
==== JUnit Vintage

* *Group ID*: `org.junit.vintage`
* *Version*: `{vintage-version}`
* *Artifact ID*:
  `junit-vintage-engine`::
    JUnit Platform 上で _昔の (vintage)_ JUnit テストを実行できるようにする JUnit Vintage
    のテストエンジン実装です。_昔の_ テストとは、JUnit 3 または JUnit 4 API で書かれたテストや、
    それらの API に依存するテスティングフレームワークを使って書かれたテストを指します。

[[dependency-metadata-junit-bom]]
==== Bill of Materials (BOM)

_Bill of Materials_ POM を使うと、
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies[Maven]
または
https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:bom_import[Gradle]
で前述のライブラリを複数参照するときに依存関係の管理を容易にすることができます。

* *Group ID*: `org.junit`
* *Artifact ID*: `junit-bom`
* *Version*: `{bom-version}`

[[dependency-metadata-dependencies]]
==== 依存関係

前述のすべての JAR が次の _@API Guardian_ JAR に依存しています。

* *Group ID*: `org.apiguardian`
* *Artifact ID*: `apiguardian-api`
* *Version*: `{apiguardian-version}`

加えて、ほとんどの JAR が次の _OpenTest4J_ JAR に直接または間接的に依存しています。

* *Group ID*: `org.opentest4j`
* *Artifact ID*: `opentest4j`
* *Version*: `{ota4j-version}`

[[dependency-diagram]]
=== 依存関係図

[plantuml, component-diagram, svg]
----
skinparam {
    defaultFontName Open Sans
}

package org.junit.jupiter {
    [junit-jupiter] as jupiter
    [junit-jupiter-api] as jupiter_api
    [junit-jupiter-engine] as jupiter_engine
    [junit-jupiter-params] as jupiter_params
    [junit-jupiter-migrationsupport] as jupiter_migration_support
}

package org.junit.vintage {
    [junit-vintage-engine] as vintage_engine
    [junit:junit] as junit4
}

package org.junit.platform {
    [junit-platform-commons] as commons
    [junit-platform-console] as console
    [junit-platform-engine] as engine
    [junit-platform-launcher] as launcher
    [junit-platform-reporting] as reporting
    [junit-platform-runner] as runner
    [junit-platform-suite-api] as suite_api
    [junit-platform-testkit] as testkit
}

package org.opentest4j {
    [opentest4j]
}

package org.apiguardian {
    [apiguardian-api] as apiguardian
    note bottom of apiguardian #white
        All artifacts except
        opentest4j and junit:junit
        have a dependency on this
        artifact. The edges have
        been omitted from this
        diagram for the sake of
        readability.
    endnote
}

jupiter ..> jupiter_api
jupiter ..> jupiter_params
jupiter ..> jupiter_engine

jupiter_api ..> opentest4j
jupiter_api ..> commons

jupiter_engine ..> engine
jupiter_engine ..> jupiter_api

jupiter_params ..> jupiter_api
jupiter_migration_support ..> jupiter_api
jupiter_migration_support ..> junit4

console ..> launcher
console ..> reporting

launcher ..> engine

engine ..> opentest4j
engine ..> commons

reporting ..> launcher

runner ..> launcher
runner ..> suite_api
runner ..> junit4

testkit ..> opentest4j
testkit ..> launcher

vintage_engine ..> engine
vintage_engine ..> junit4
----
