[[migrating-from-junit4]]
== JUnit 4からの移行

JUnit Jupiterのプログラミングモデルと拡張モデルは、`Rule` や `Runner`
のようなJUnit 4の機能をネイティブにはサポートしていません。しかし、
ソースコードのメンテナがJUnit Jupiterへ移行するためにすべての既存テストやテスト拡張、
カスタムビルド基盤を書き換えることを求めているわけではありません。

代わりに、JUnit Platform上でJUnit 3またはJUnit 4ベースの既存テストを実行できる
ようにする _JUnit Vintageテストエンジン_ を通して、なだらかな移行パスを提供しています。
JUnit Jupiter固有のクラスやアノテーションはすべて新設された `org.junit.jupiter`
パッケージ配下にあるため、JUnit 4とJUnit Jupiterが同時にクラスパスに含まれていても
コンフリクトは発生しません。そのため、既存のJUnit 4テストをJUnit Jupiter
テストと並行してメンテナンスしても安全です。さらに、JUnitチームはJUnit 4.x
系のメンテナンスとバグフィックスリリースを継続しているため、
開発者は自身のスケジュールに合わせてJUnit Jupiterに移行する十分な時間があります。


[[migrating-from-junit4-running]]
=== JUnit Platform上でJUnit 4テストを実行する

`junit-vintage-engine` がテストランタイムパスに含まれていることを確認してください。
そうすれば、JUnit Platformランチャーが、JUnit 3およびJUnit 4のテストを自動的に
ピックアップしてくれます。

{junit5-samples-repo}[`junit5-samples`] リポジトリにあるサンプルプロジェクトを
参照して、GradleやMavenでどのように実現するか確認してください。

[[migrating-from-junit4-categories-support]]
==== カテゴリのサポート

`@Category` アノテーションの付与されたテストクラスやテストメソッドに対しては、
_JUnit Vintageテストエンジン_ はカテゴリの完全修飾クラス名を該当テストのタグとみなします。
例えば、テストメソッドに `@Category(Example.class)` アノテーションが付与されている場合、
`"com.acme.Example"` でタグ付けされます。JUnit 4の `Categories` ランナーと同様に、
この情報は実行するテストのフィルタリングに使われます (詳細は、<<running-tests>> 参照)。


[[migrating-from-junit4-tips]]
=== 移行のヒント

既存のJUnit 4テストをJUnit Jupiterに移行するときに気をつけなければいけないことは、
次の通りです。

* Annotations reside in the `org.junit.jupiter.api` package.
* Assertions reside in `org.junit.jupiter.api.Assertions`.
  - Note that you may continue to use assertion methods from `org.junit.Assert` or any
    other assertion library such as {AssertJ}, {Hamcrest}, {Truth}, etc.
* Assumptions reside in `org.junit.jupiter.api.Assumptions`.
  - Note that JUnit Jupiter 5.4 and later versions support methods from JUnit 4's
    `org.junit.Assume` class for assumptions. Specifically, JUnit Jupiter supports JUnit
    4's `AssumptionViolatedException` to signal that a test should be aborted instead of
    marked as a failure.
* `@Before` and `@After` no longer exist; use `@BeforeEach` and `@AfterEach` instead.
* `@BeforeClass` and `@AfterClass` no longer exist; use `@BeforeAll` and `@AfterAll`
  instead.
* `@Ignore` no longer exists: use `@Disabled` or one of the other built-in
  <<writing-tests-conditional-execution, execution conditions>> instead
  - See also <<migrating-from-junit4-ignore-annotation-support>>.
* `@Category` no longer exists; use `@Tag` instead.
* `@RunWith` no longer exists; superseded by `@ExtendWith`.
* `@Rule` and `@ClassRule` no longer exist; superseded by `@ExtendWith` and
  `@RegisterExtension`
  - See also <<migrating-from-junit4-rule-support>>.


[[migrating-from-junit4-rule-support]]
=== JUnit 4のルールの限定的なサポート

前述したように、JUnit JupiterはJUnit 4のルールをサポートしていませんし、
その予定もありません。しかし、JUnitチームは、多くの組織が（特に大きな組織ほど）
カスタムルールを使ったJUnit 4のコードベースを保持していることを理解しています。
このような組織に段階的な移行パスを用意するため、JUnitチームはJUnit Jupiter
でJUnit 4のルールをサポートすることを決めました。
このサポートはアダプタをベースにしており、JUnit Jupiterの拡張モデルと意味的に
互換性があるルールに限定されています。
例えば、テストの実行フローを完全に変えてしまうようなことがないものです。

JUnit Jupiterの `junit-jupiter-migrationsupport` モジュールは、
今のところ次の3つの `Rule` とそのサブクラスをサポートしています。

* `org.junit.rules.ExternalResource` (`org.junit.rules.TemporaryFolder` も含む)
* `org.junit.rules.Verifier` (`org.junit.rules.ErrorCollector` も含む)
* `org.junit.rules.ExpectedException`

JUnit 4と同様に、Ruleアノテーションが付与されたフィールドとメソッドをサポートします。
これらのクラスレベルの拡張機能を使うことで、レガシーコードがもつ `Rule`
実装をJUnit 4のimport文も含めて _変更せずにそのままにしておく_ ことができます。

This limited form of `Rule` support can be switched on by the class-level annotation
`{EnableRuleMigrationSupport}`. This annotation is a _composed annotation_ which enables
all rule migration support extensions: `VerifierSupport`, `ExternalResourceSupport`, and
`ExpectedExceptionSupport`. You may alternatively choose to annotate your test class with
`@EnableJUnit4MigrationSupport` which registers migration support for rules _and_ JUnit
4's `@Ignore` annotation (see <<migrating-from-junit4-ignore-annotation-support>>).

なお、JUnit 5に対する新しい拡張機能を開発するときには、JUnit 4
のルールベースのモデルではなく、JUnit Jupiterの拡張モデルを使ってください。

WARNING: JUnit JupiterにおけるJUnit 4の `Rule` サポートは、今のところ
_実験的な_ 機能です。詳細は、<<api-evolution-experimental-apis>>
の表を確認してください。


[[migrating-from-junit4-ignore-annotation-support]]
=== JUnit 4 @Ignore Support

In order to provide a smooth migration path from JUnit 4 to JUnit Jupiter, the
`junit-jupiter-migrationsupport` module provides support for JUnit 4's `@Ignore`
annotation analogous to Jupiter's `{Disabled}` annotation.

To use `@Ignore` with JUnit Jupiter based tests, configure a _test_ dependency on the
`junit-jupiter-migrationsupport` module in your build and then annotate your test class
with `@ExtendWith(IgnoreCondition.class)` or `{EnableJUnit4MigrationSupport}` (which
automatically registers the `IgnoreCondition` along with
<<migrating-from-junit4-rule-support>>). The `IgnoreCondition` is an
`{ExecutionCondition}` that disables test classes or test methods that are annotated with
`@Ignore`.

[source,java,indent=0]
----
include::{testDir}/example/IgnoredTestsDemo.java[tags=user_guide]
----

WARNING: JUnit 4 `@Ignore` support in JUnit Jupiter is currently an _experimental_
feature. Consult the table in <<api-evolution-experimental-apis>> for detail.
