[[migrating-from-junit4]]
== JUnit 4からの移行

JUnit Jupiterのプログラミングモデルと拡張モデルは、`Rule` や `Runner`
のようなJUnit 4の機能をネイティブにはサポートしていません。しかし、
ソースコードのメンテナがJUnit Jupiterへ移行するためにすべての既存テストやテスト拡張、
カスタムビルド基盤を書き換えることを求めているわけではありません。

代わりに、JUnit Platform上でJUnit 3またはJUnit 4ベースの既存テストを実行できる
ようにする _JUnit Vintageテストエンジン_ を通して、なだらかな移行パスを提供しています。
JUnit Jupiter固有のクラスやアノテーションはすべて新設された `org.junit.jupiter`
パッケージ配下にあるため、JUnit 4とJUnit Jupiterが同時にクラスパスに含まれていても
コンフリクトは発生しません。そのため、既存のJUnit 4テストをJUnit Jupiter
テストと並行してメンテナンスしても安全です。さらに、JUnitチームはJUnit 4.x
系のメンテナンスとバグフィックスリリースを継続しているため、
開発者は自身のスケジュールに合わせてJUnit Jupiterに移行する十分な時間があります。

[[migrating-from-junit4-running]]
=== JUnit Platform上でJUnit 4テストを実行する

`junit-vintage-engine` がテストランタイムパスに含まれていることを確認してください。
そうすれば、JUnit Platformランチャーが、JUnit 3およびJUnit 4のテストを自動的に
ピックアップしてくれます。

{junit5-samples-repo}[`junit5-samples`] リポジトリにあるサンプルプロジェクトを
参照して、GradleやMavenでどのように実現するか確認してください。

[[migrating-from-junit4-categories-support]]
==== カテゴリのサポート

`@Category` アノテーションの付与されたテストクラスやテストメソッドに対しては、
_JUnit Vintageテストエンジン_ はカテゴリの完全修飾クラス名を該当テストのタグとみなします。
例えば、テストメソッドに `@Category(Example.class)` アノテーションが付与されている場合、
`"com.acme.Example"` でタグ付けされます。JUnit 4の `Categories` ランナーと同様に、
この情報は実行するテストのフィルタリングに使われます (詳細は、<<running-tests>> 参照)。

[[migrating-from-junit4-tips]]
=== 移行のヒント

既存のJUnit 4テストをJUnit Jupiterに移行するときに気をつけなければいけないことは、
次の通りです。

* アノテーションは、`org.junit.jupiter.api` パッケージにあります。
* アサーションは、`org.junit.jupiter.api.Assertions` にあります。
* 前提条件は、`org.junit.jupiter.api.Assumptions` にあります。
* `@Before` と `@After` は、なくなりました。代わりに、`@BeforeEach` と `@AfterEach` を使ってください。
* `@BeforeClass` と `@AfterClass` は、なくなりました。代わりに、`@BeforeAll` と `@AfterAll` を使ってください。
* `@Ignore` は、なくなりました。代わりに、`@Disabled` を使ってください。
* `@Category` は、なくなりました。代わりに、`@Tag` を使ってください。
* `@RunWith` は、なくなりました。`@ExtendWith` に置き換えられました。
* `@Rule` と `@ClassRule` は、なくなりました。`@ExtendWith` に置き換えられました。
   部分的なルールのサポートについては、次節を参照してください。

[[migrating-from-junit4-rule-support]]
=== JUnit 4のルールの限定的なサポート

前述したように、JUnit JupiterはJUnit 4のルールをサポートしていませんし、
その予定もありません。しかし、JUnitチームは、多くの組織が（特に大きな組織ほど）
カスタムルールを使ったJUnit 4のコードベースを保持していることを理解しています。
このような組織に段階的な移行パスを用意するため、JUnitチームはJUnit Jupiter
でJUnit 4のルールをサポートすることを決めました。
このサポートはアダプタをベースにしており、JUnit Jupiterの拡張モデルと意味的に
互換性があるルールに限定されています。
例えば、テストの実行フローを完全に変えてしまうようなことがないものです。

JUnit Jupiterの `junit-jupiter-migrationsupport` モジュールは、
今のところ次の3つの `Rule` とそのサブクラスをサポートしています。

* `org.junit.rules.ExternalResource` (`org.junit.rules.TemporaryFolder` も含む)
* `org.junit.rules.Verifier` (`org.junit.rules.ErrorCollector` も含む)
* `org.junit.rules.ExpectedException`

JUnit 4と同様に、Ruleアノテーションが付与されたフィールドとメソッドをサポートします。
これらのクラスレベルの拡張機能を使うことで、レガシーコードがもつ `Rule`
実装をJUnit 4のimport文も含めて _変更せずにそのままにしておく_ ことができます。

この限定的な形での `Rule` サポートは、クラスレベルのアノテーション
`org.junit.jupiter.migrationsupport.rules.EnableRuleMigrationSupport`
を使って有効にすることができます。このアノテーションは、
`VerifierSupport`, `ExternalResourceSupport`, `ExpectedExceptionSupport`
のすべての移行サポート拡張を有効にするための _合成アノテーション_ になっています。

なお、JUnit 5に対する新しい拡張機能を開発するときには、JUnit 4
のルールベースのモデルではなく、JUnit Jupiterの拡張モデルを使ってください。

WARNING: JUnit JupiterにおけるJUnit 4の `Rule` サポートは、今のところ
_実験的な_ 機能です。詳細は、<<api-evolution-experimental-apis>>
の表を確認してください。
