[[migrating-from-junit4]]
== JUnit 4からの移行

JUnit Jupiterのプログラミングモデルと拡張モデルは、`Rule` や `Runner`
のようなJUnit 4の機能をネイティブにはサポートしていません。しかし、
ソースコードのメンテナがJUnit Jupiterへ移行するためにすべての既存テストやテスト拡張、
カスタムビルド基盤を書き換えることを求めているわけではありません。

代わりに、JUnit Platform上でJUnit 3またはJUnit 4ベースの既存テストを実行できる
ようにする _JUnit Vintageテストエンジン_ を通して、なだらかな移行パスを提供しています。
JUnit Jupiter固有のクラスやアノテーションはすべて新設された `org.junit.jupiter`
パッケージ配下にあるため、JUnit 4とJUnit Jupiterが同時にクラスパスに含まれていても
コンフリクトは発生しません。そのため、既存のJUnit 4テストをJUnit Jupiter
テストと並行してメンテナンスしても安全です。さらに、JUnitチームはJUnit 4.x
系のメンテナンスとバグフィックスリリースを継続しているため、
開発者は自身のスケジュールに合わせてJUnit Jupiterに移行する十分な時間があります。

[[migrating-from-junit4-running]]
=== JUnit Platform上でJUnit 4テストを実行する

`junit-vintage-engine` がテストランタイムパスに含まれていることを確認してください。
そうすれば、JUnit Platformランチャーが、JUnit 3およびJUnit 4のテストを自動的に
ピックアップしてくれます。

{junit5-samples-repo}[`junit5-samples`] リポジトリにあるサンプルプロジェクトを
参照して、GradleやMavenでどのように実現するか確認してください。

[[migrating-from-junit4-categories-support]]
==== カテゴリのサポート

`@Category` アノテーションの付与されたテストクラスやテストメソッドに対しては、
_JUnit Vintageテストエンジン_ はカテゴリの完全修飾クラス名を該当テストのタグとみなします。
例えば、テストメソッドに `@Category(Example.class)` アノテーションが付与されている場合、
`"com.acme.Example"` でタグ付けされます。JUnit 4の `Categories` ランナーと同様に、
この情報は実行するテストのフィルタリングに使われます (詳細は、<<running-tests>> 参照)。

[[migrating-from-junit4-tips]]
=== Migration Tips

The following are things you have to watch out for when migrating existing JUnit 4 tests
to JUnit Jupiter.

* Annotations reside in the `org.junit.jupiter.api` package.
* Assertions reside in `org.junit.jupiter.api.Assertions`.
* Assumptions reside in `org.junit.jupiter.api.Assumptions`.
* `@Before` and `@After` no longer exist; use `@BeforeEach` and `@AfterEach` instead.
* `@BeforeClass` and `@AfterClass` no longer exist; use `@BeforeAll` and `@AfterAll` instead.
* `@Ignore` no longer exists: use `@Disabled` instead.
* `@Category` no longer exists; use `@Tag` instead.
* `@RunWith` no longer exists; superseded by `@ExtendWith`.
* `@Rule` and `@ClassRule` no longer exist; superseded by `@ExtendWith`;
   see the following section for partial rule support.

[[migrating-from-junit4-rule-support]]
=== Limited JUnit 4 Rule Support

As stated above, JUnit Jupiter does not and will not support JUnit 4 rules natively. The
JUnit team realizes, however, that many organizations, especially large ones, are likely
to have large JUnit 4 code bases that make use of custom rules. To serve these
organizations and enable a gradual migration path the JUnit team has decided to support a
selection of JUnit 4 rules verbatim within JUnit Jupiter. This support is based on
adapters and is limited to those rules that are semantically compatible to the JUnit
Jupiter extension model, i.e. those that do not completely change the overall execution
flow of the test.

The `junit-jupiter-migrationsupport` module from JUnit Jupiter currently supports the
following three `Rule` types including subclasses of those types:

* `org.junit.rules.ExternalResource` (including `org.junit.rules.TemporaryFolder`)
* `org.junit.rules.Verifier` (including `org.junit.rules.ErrorCollector`)
* `org.junit.rules.ExpectedException`

As in JUnit 4, Rule-annotated fields as well as methods are supported. By using these
class-level extensions on a test class such `Rule` implementations in legacy code bases
can be _left unchanged_ including the JUnit 4 rule import statements.

This limited form of `Rule` support can be switched on by the class-level annotation
`org.junit.jupiter.migrationsupport.rules.EnableRuleMigrationSupport`. This annotation is
a _composed annotation_ which enables all migration support extensions:
`VerifierSupport`, `ExternalResourceSupport`, and `ExpectedExceptionSupport`.

However, if you intend to develop a new extension for JUnit 5 please use the new
extension model of JUnit Jupiter instead of the rule-based model of JUnit 4.

WARNING: JUnit 4 `Rule` support in JUnit Jupiter is currently an _experimental_ feature.
Consult the table in <<api-evolution-experimental-apis>> for detail.
