[[overview]]
== 概要

この文書は、テストを書くプログラマーや拡張機能の作者、ビルドツールやIDEを含むテストエンジンの作者に対して、
包括的なリファレンスを提供することを目的としています。

//ifdef::linkToPdf[]
//ifdef::backend-html5[]
//This document is also available as a link:index.pdf[PDF download].
//endif::backend-html5[]
//endif::linkToPdf[]

[TIP]
.Translations
====
『JUnit 5 User Guide』の
https://junit.org/junit5/docs/{docs-version}/user-guide/[v{docs-version}]
時点の日本語訳です。最新の情報は、
https://junit.org/junit5/docs/current/user-guide/[公式サイト] を参照してください。
誤訳や誤植などのフィードバックは、
https://github.com/oohira/junit5-doc-jp[GitHub] または https://twitter.com/oohira[@oohira]
までお願いします。
====

[[overview-what-is-junit-5]]
=== JUnit 5とは

これまでのバージョンのJUnitとは異なり、JUnit 5は
3つのサブプロジェクトに含まれる複数のモジュールで構成されます。

**JUnit 5 = _JUnit Platform_ + _JUnit Jupiter_ + _JUnit Vintage_**

**JUnit Platform** は、JVM上で <<launcher-api,テストフレームワークを起動する>>
ための基盤となります。また、このプラットフォーム上で動作するテストフレームワークを開発するための
`{TestEngine}` APIも定義しています。加えて、コマンドラインからプラットフォームを起動するための
<<running-tests-console-launcher,Console Launcher>> や、JUnit 4ベースの環境で
プラットフォームを起動して任意の `TestEngine` を実行するための
<<running-tests-junit-platform-runner,JUnit 4ベースのテストランナー>>
などを提供します。主要なIDE (<<running-tests-ide-intellij-idea>> や
<<running-tests-ide-eclipse>>, <<running-tests-ide-netbeans>>,
<<running-tests-ide-vscode>> を参照) やビルドツール (<<running-tests-build-gradle>>
や <<running-tests-build-maven>>, <<running-tests-build-ant>> を参照) で
JUnit Platformがサポートされています。

**JUnit Jupiter** は、JUnit 5でテストや拡張機能を書くための新しい
<<writing-tests,プログラミングモデル>> と <<extensions,拡張モデル>> の組み合わせです。
Jupiterサブプロジェクトは、プラットフォーム上でJupiterベースのテストを実行するための
`TestEngine` を提供します。

**JUnit Vintage** は、プラットフォーム上でJUnit 3またはJUnit 4
ベースのテストを実行するための `TestEngine` を提供します。

[[overview-java-versions]]
=== サポートされるJavaバージョン

JUnit 5を実行するには、Java 8（またはそれ以上）が必要となります。
ただし、それより古いバージョンのJDKでコンパイルされたコードをテストすることは可能です。

[[overview-getting-help]]
=== 助けてもらうには

{StackOverflow} で質問するか、 {Gitter} で私たちにチャットしてください。

[[overview-getting-started]]
=== 始めるには

[[overview-getting-started-junit-artifacts]]
==== JUnit 成果物のダウンロード

ダウンロードしてプロジェクトに取り込める成果物を見つけるためには、<<dependency-metadata>>
を参照してください。ビルドの依存管理を設定するには、<<running-tests-build>> と
<<overview-getting-started-example-projects>> を参照してください。

[[overview-getting-started-features]]
==== JUnit 5 の機能

JUnit 5 で利用可能な機能とその使い方を知るためには、トピックごとに構成されている
このユーザーガイドの該当セクションを読んでください。

* <<writing-tests, JUnit Jupiter でテストを書く>>
* <<migrating-from-junit4, JUnit 4 から JUnit Jupiter に移行する>>
* <<running-tests>>
* <<extensions, JUnit Jupiter の拡張モデル>>
* 高度なトピック
  - <<launcher-api>>
  - <<testkit>>

[[overview-getting-started-example-projects]]
==== サンプルプロジェクト

コピーして試せる完全に動作するプロジェクトの例としては、 {junit5-samples-repo}[`junit5-samples`]
リポジトリがよい出発点となるでしょう。`junit5-samples` リポジトリは、JUnit JupiterやJUnit Vintage、
その他のテストフレームワークをベースとした、様々なプロジェクトのサンプルを提供します。
サンプルプロジェクトから適切なビルドスクリプト（例えば、`build.gradle` や `pom.xml` など）
を見つけられるでしょう。以下のリンクは、その中から選択できるいくつかの組み合わせです。

* GradleとJavaの場合は、`{junit5-jupiter-starter-gradle}` プロジェクトを参照してください
* GradleとKotlinの場合は、`{junit5-jupiter-starter-gradle-kotlin}` プロジェクトを参照してください
* GradleとGroovyの場合は、`{junit5-jupiter-starter-gradle-groovy}` プロジェクトを参照してください
* Mavenの場合は、`{junit5-jupiter-starter-maven}` プロジェクトを参照してください
* Antの場合は、`{junit5-jupiter-starter-ant}` プロジェクトを参照してください
