[[overview]]
== 概要

この文書は、テストを書くプログラマーや拡張機能の作者、ビルドツールやIDEを含むテストエンジンの作者に対して、
包括的なリファレンスを提供することを目的としています。

//ifdef::backend-html5[This document is also available as a link:index.pdf[PDF download].]

[TIP]
.Translations
====
『JUnit 5 User Guide』の
https://junit.org/junit5/docs/{docs-version}/user-guide/[v{docs-version}]
時点の日本語訳です。最新の情報は、
https://junit.org/junit5/docs/current/user-guide/[公式サイト] を参照してください。
誤訳や誤植などのフィードバックは、
https://github.com/oohira/junit5-doc-jp[GitHub] または https://twitter.com/oohira[@oohira]
までお願いします。
====

[[overview-what-is-junit-5]]
=== JUnit 5とは

これまでのバージョンのJUnitとは異なり、JUnit 5は
3つのサブプロジェクトに含まれる複数のモジュールで構成されます。

**JUnit 5 = _JUnit Platform_ + _JUnit Jupiter_ + _JUnit Vintage_**

**JUnit Platform** は、JVM上で <<launcher-api,テストフレームワークを起動する>>
ための基盤となり、このプラットフォーム上で動作するテストフレームワークを開発するための
`{TestEngine}` APIを定義しています。加えて、コマンドラインからプラットフォームを起動するための
<<running-tests-console-launcher,Console Launcher>> や、
<<running-tests-build-gradle,Gradle>> と <<running-tests-build-maven,Maven>>
用のビルドプラグイン、 <<running-tests-junit-platform-runner,JUnit 4ベースのテストランナー>>
などを提供し、あらゆる `TestEngine` を実行できるようになっています。

**JUnit Jupiter** は、JUnit 5でテストや拡張機能を書くための新しい
<<writing-tests,プログラミングモデル>> と <<extensions,拡張モデル>> の組み合わせです。
Jupiterサブプロジェクトは、プラットフォーム上でJupiterベースのテストを実行するための
`TestEngine` を提供します。

**JUnit Vintage** は、プラットフォーム上でJUnit 3またはJUnit 4
ベースのテストを実行するための `TestEngine` を提供します。

[[overview-java-versions]]
=== サポートされるJavaバージョン

JUnit 5を実行するには、Java 8（またはそれ以上）が必要となります。
ただし、それより古いバージョンのJDKでコンパイルされたコードをテストすることは可能です。


[[overview-getting-help]]
=== 助けてもらうには

{StackOverflow} で質問するか、 {Gitter} で私たちにチャットしてください。

[[installation]]
== インストール

最終リリースや各マイルストーンでの成果物は、Maven Centralリポジトリにデプロイされています。

スナップショットは、Sonatype {snapshot-repo}[スナップショットリポジトリ] の
{snapshot-repo}/org/junit/[/org/junit] 以下にデプロイされています。

[[dependency-metadata]]
=== 依存関係メタデータ

[[dependency-metadata-junit-platform]]
==== JUnit Platform

* *Group ID*: `org.junit.platform`
* *Version*: `{platform-version}`
* *Artifact IDs*:
  `junit-platform-commons`::
    JUnitの内部的な共通ライブラリ／ユーティリティです。これらのユーティリティは、
    JUnitフレームワーク自身で使われることだけを想定しています。
    _外部のプログラムからの利用はサポートされていません。_ 利用は自己責任で！
  `junit-platform-console`::
    コンソールからJUnit Platform上でテストを見つけて実行する機能を提供します。
    詳細は、 <<running-tests-console-launcher>> を参照してください。
  `junit-platform-console-standalone`::
    すべての依存関係を含む実行可能なJARは、Maven Centralリポジトリの
    https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone[junit-platform-console-standalone]
    ディレクトリで提供されています。詳細は、 <<running-tests-console-launcher>> を参照してください。
  `junit-platform-engine`::
    テストエンジンの公開APIです。詳細は、 <<launcher-api-engines-custom>> を参照してください。
  `junit-platform-gradle-plugin`::
    <<running-tests-build-gradle,Gradle>> を使って、
    JUnit Platform上でテストを見つけて実行する機能を提供します。
  `junit-platform-launcher`::
    テストプランを構成して起動するための公開APIです。通常は、IDEやビルドツールに使われます。
    詳細は、 <<launcher-api>> を参照してください。
  `junit-platform-runner`::
    JUnit Platform上のテストおよびテストスイートをJUnit 4環境で実行するテストランナーです。
    詳細は、 <<running-tests-junit-platform-runner>> を参照してください。
  `junit-platform-suite-api`::
    JUnit Platform上でテストスイートを構成するためのアノテーションです。
    <<running-tests-junit-platform-runner,JUnitPlatformランナー>>
    と（おそらく）サードパーティーの `TestEngine` 実装にもサポートされます。
  `junit-platform-surefire-provider`::
    <<running-tests-build-maven,Maven Surefire>> を使って、
    JUnit Platform上でテストを見つけて実行する機能を提供します。

[[dependency-metadata-junit-jupiter]]
==== JUnit Jupiter

* *Group ID*: `org.junit.jupiter`
* *Version*: `{jupiter-version}`
* *Artifact IDs*:
  `junit-jupiter-api`::
    JUnit Jupiterで <<writing-tests,テスト>> や <<extensions,拡張機能>> を書くためのAPIです。
  `junit-jupiter-engine`::
    JUnit Jupiterのテストエンジン実装です。実行時だけ必要になります。
  `junit-jupiter-params`::
    JUnit Jupiterで <<writing-tests-parameterized-tests,パラメーター化テスト>> をサポートします。
  `junit-jupiter-migrationsupport`::
    JUnit 4からJUnit Jupiterへの移行をサポートします。
    JUnit Jupiter上で、JUnit 4ルールを実行したいときだけ必要になります。

[[dependency-metadata-junit-vintage]]
==== JUnit Vintage

* *Group ID*: `org.junit.vintage`
* *Version*: `{vintage-version}`
* *Artifact ID*:
  `junit-vintage-engine`::
    JUnit Vintageのテストエンジン実装です。JUnit 3またはJUnit 4で書かれた昔のテストを
    新しいJUnit Platform上で実行できるようにします。

[[dependency-metadata-dependencies]]
==== 依存関係

前述のすべてのJARが次の _@API Guardian_ JARに依存しています。

* *Group ID*: `org.apiguardian`
* *Artifact ID*: `apiguardian-api`
* *Version*: `{apiguardian-version}`

加えて、ほとんどのJARが次の _OpenTest4J_ JARに直接または間接的に依存しています。

* *Group ID*: `org.opentest4j`
* *Artifact ID*: `opentest4j`
* *Version*: `{ota4j-version}`

[[dependency-diagram]]
=== 依存関係図

[plantuml, component-diagram, svg]
----
skinparam {
    defaultFontName Open Sans
}

package org.junit.jupiter {
    [junit-jupiter-api] as jupiter_api
    [junit-jupiter-engine] as jupiter_engine
    [junit-jupiter-params] as jupiter_params
    [junit-jupiter-migrationsupport] as jupiter_migration_support
}

package org.junit.vintage {
    [junit-vintage-engine] as vintage_engine
    [junit:junit] as junit4
}

package org.junit.platform {
    [junit-platform-commons] as commons
    [junit-platform-console] as console
    [junit-platform-engine] as engine
    [junit-platform-gradle-plugin] as gradle
    [junit-platform-launcher] as launcher
    [junit-platform-runner] as runner
    [junit-platform-suite-api] as suite_api
    [junit-platform-surefire-provider] as surefire
}

package org.opentest4j {
    [opentest4j]
}

package org.apiguardian {
    [apiguardian-api] as apiguardian
    note bottom of apiguardian #white
        All artifacts except
        opentest4j and junit:junit
        have a dependency on this
        artifact. The edges have
        been omitted from this
        diagram for the sake of
        readability.
    endnote
}

jupiter_api ..> opentest4j
jupiter_api ..> commons

jupiter_engine ..> engine
jupiter_engine ..> jupiter_api

jupiter_params ..> jupiter_api
jupiter_migration_support ..> jupiter_api
jupiter_migration_support ..> junit4

console ..> launcher

gradle ..> console

launcher ..> engine

engine ..> opentest4j
engine ..> commons

runner ..> launcher
runner ..> suite_api
runner ..> junit4

suite_api ..> commons

surefire ..> launcher

vintage_engine ..> engine
vintage_engine ..> junit4
----

[[dependency-metadata-junit-jupiter-samples]]
=== JUnit Jupiterサンプルプロジェクト

{junit5-samples-repo}[`junit5-samples`] リポジトリは、
JUnit JupiterベースとJUnit Vintageベースのプロジェクトの様々なサンプルを提供します。
次のプロジェクトで `build.gradle` と `pom.xml` を見つけられるでしょう。

* Gradleの場合は、`{junit5-gradle-consumer}` プロジェクトを参照してください
* Mavenの場合は、`{junit5-maven-consumer}` プロジェクトを参照してください
